<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCNOk54S\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCNOk54S/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCNOk54S.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCNOk54S\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCNOk54S\App_KernelDevDebugContainer([
    'container.build_hash' => 'CNOk54S',
    'container.build_id' => '2f8c54a1',
    'container.build_time' => 1601296493,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCNOk54S');
