<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4DKtyKX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4DKtyKX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4DKtyKX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4DKtyKX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4DKtyKX\App_KernelDevDebugContainer([
    'container.build_hash' => '4DKtyKX',
    'container.build_id' => 'f34ed0bf',
    'container.build_time' => 1601292942,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4DKtyKX');
